name: Publish Package

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write # Required for provenance
      attestations: write
      artifact-metadata: write
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v5
        with:
          version: 10
          cache: true
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://npm.pkg.github.com'
          scope: 'wilton-henao'
      - name: Install and Build
        run: pnpm install --frozen-lockfile && pnpm run build

      # - name: Pack Package
      #   id: pack
      #   run: |
      #     export HUSKY=0
      #     pnpm pack

      # - name: Generate SLSA Attestation
      #   uses: actions/attest@v4
      #   with:
      #     subject-path: "*.tgz"
      #     github-token: ${{ secrets.MY_PAT }}

      # - name: Publish Package
      #   run: pnpm publish *.tgz --no-git-checks --access restricted
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.MY_PAT }}

      - name: Publish to npm
        id: publish
        run: pnpm publish --no-git-checks --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.MY_PAT }}